# Generated by Django 4.1.5 on 2023-11-23 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_remove_shoppingcart_customer_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
