# Generated by Django 4.1.5 on 2023-11-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_devicemodel_status_alter_devicemodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device',
        ),
    ]
