# Generated by Django 4.1.5 on 2023-11-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
