# Generated by Django 4.1.5 on 2023-11-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_device_imei_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_imei',
            name='owner',
        ),
    ]
