# Generated by Django 4.1.5 on 2023-11-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='Inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.inventory'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
