# Generated by Django 4.1.5 on 2023-11-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_inventory_product_product_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
