# Generated by Django 4.1.5 on 2023-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_imei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Shopping Carts'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartdetail',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Shopping Cart Details'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.AddField(
            model_name='device',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
