# Generated by Django 4.1.5 on 2023-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_inventory_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
