# Generated by Django 4.1.5 on 2023-11-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_return_condition_alter_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
