# Generated by Django 4.1.5 on 2023-12-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_department_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id'], 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['id'], 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['id'], 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['id'], 'verbose_name_plural': 'Shopping Carts'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartdetail',
            options={'ordering': ['id'], 'verbose_name_plural': 'Shopping Cart Details'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id'], 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['id'], 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.RemoveField(
            model_name='shoppingcartdetail',
            name='created_at',
        ),
    ]
