# Generated by Django 4.1.5 on 2023-11-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_return_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-review_date'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
