# Generated by Django 4.1.5 on 2023-12-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_department_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
