# Generated by Django 4.1.5 on 2023-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_device_issues_workorder_device_workorder_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
