# Generated by Django 4.1.5 on 2023-11-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
