# Generated by Django 4.1.5 on 2023-11-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_supplier_part_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='part_cost',
            field=models.DecimalField(decimal_places=2, default=888.88, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=888.88, max_digits=10),
        ),
    ]
