# Generated by Django 4.1.5 on 2023-12-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
