# Generated by Django 4.1.5 on 2023-11-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_servicedetail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.servicedetail'),
        ),
    ]
