# Generated by Django 4.1.5 on 2024-01-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_device_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.shoppingcart",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cart Payments",
                "ordering": ["id"],
            },
        ),
    ]
