# Generated by Django 4.1.5 on 2024-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_cartpayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartpayment",
            old_name="amount",
            new_name="cash_amount",
        ),
        migrations.RemoveField(
            model_name="cartpayment",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="cartpayment",
            name="change_due",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartpayment",
            name="credit_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
