# Generated by Django 4.1.5 on 2023-11-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_service_workorderdetail_service_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='part',
        ),
    ]
