# Generated by Django 4.1.5 on 2023-12-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_options_remove_order_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('on_hold', 'On Hold')], default='awaiting_payment', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='transaction_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
