# Generated by Django 4.1.5 on 2024-01-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_rename_amount_cartpayment_cash_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartpayment",
            name="cash_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartpayment",
            name="change_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartpayment",
            name="credit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
