# Generated by Django 4.1.5 on 2023-11-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_servicedetail_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderdetail',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.part'),
        ),
    ]
