# Generated by Django 4.1.5 on 2024-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_cartpayment_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
